package main

import (
	"database/sql"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"
	"time"
)

const agentInfoGeneratedFile = "AGENTS.generated.md"

const agentInfoMarkdownHeader = "<!-- AUTO-GENERATED by `go-trader agent-info`. Do not edit by hand; edits are overwritten on update. Human notes belong in CLAUDE.md. -->"

type agentCommand struct {
	Name    string   `json:"name"`
	Summary string   `json:"summary"`
	Usage   string   `json:"usage"`
	Flags   []string `json:"flags,omitempty"`
}

var agentInfoCommands = []agentCommand{
	{Name: "(daemon)", Summary: "Run the scheduler loop (default when no subcommand is given).", Usage: "go-trader [--config <path>] [--once] [--summary <channel>] [--leaderboard] [--status-port <n>]", Flags: []string{"--config", "--once", "--summary", "--leaderboard", "--status-port"}},
	{Name: "agent-info", Summary: "Emit this self-describing capability + runtime-state report.", Usage: "go-trader agent-info [--config <path>] [--bootstrap-md] [--append-changelog] [--output <path>]", Flags: []string{"--config", "--bootstrap-md", "--append-changelog", "--output"}},
	{Name: "init", Summary: "Generate a config.json interactively or from JSON.", Usage: "go-trader init [--json <json>] [--output <path>]"},
	{Name: "export", Summary: "Export trade history (e.g. TradingView CSV).", Usage: "go-trader export tradingview [...]"},
	{Name: "manual-open", Summary: "Open a manual position (kill-switch + circuit-breaker guarded).", Usage: "go-trader manual-open [...]"},
	{Name: "manual-add", Summary: "Scale into an existing manual position.", Usage: "go-trader manual-add [...]"},
	{Name: "manual-close", Summary: "Close (or partially close) a manual position.", Usage: "go-trader manual-close [...]"},
	{Name: "force-close", Summary: "Close (or partially close) a live Hyperliquid perps strategy position.", Usage: "go-trader force-close <strategy-id> [--qty N] [--dry-run]"},
	{Name: "manual-cancel", Summary: "Cancel a resting manual limit order.", Usage: "go-trader manual-cancel [...]"},
	{Name: "manual-update-sl", Summary: "Move the stop-loss trigger on a manual position.", Usage: "go-trader manual-update-sl <strategy-id> --trigger N [--symbol Y] [--dry-run]"},
	{Name: "manual-cancel-sl", Summary: "Cancel the resting stop-loss on a manual position.", Usage: "go-trader manual-cancel-sl <strategy-id> [--symbol Y] [--dry-run]"},
	{Name: "backfill", Summary: "Backfill derived data (trade-ledger fees/PnL, HL fees).", Usage: "go-trader backfill <trade-ledger|hl-fees> [...]"},
	{Name: "probe", Summary: "Run startup probes against the configured check scripts.", Usage: "go-trader probe [--config <path>]"},
	{Name: "inspect", Summary: "Print a strategy's effective (post-migration, post-default) config.", Usage: "go-trader inspect [--config <path>] [--json] <strategy-id>|--all"},
	{Name: "diagnostics", Summary: "Read-only per-strategy trade-quality report (MFE/MAE/capture ratio) with backtestable tuning hypotheses (#1147).", Usage: "go-trader diagnostics [--config <path>] [--db <path>] [--strategy <id>] [--min-trades N] [--min-bucket N]", Flags: []string{"--config", "--db", "--strategy", "--min-trades", "--min-bucket"}},
	{Name: "version", Summary: "Print the binary version.", Usage: "go-trader version"},
}

type agentEnvVar struct {
	Name    string `json:"name"`
	Purpose string `json:"purpose"`
	Secret  bool   `json:"secret"`
	Set     bool   `json:"set"`
}

var agentInfoEnvVars = []agentEnvVar{
	{Name: "ANTHROPIC_API_KEY", Purpose: "Anthropic API key for the #1137 LLM entry-analysis pipeline (shared_scripts/llm_review.py); Go only checks presence to warn when analysis is enabled without it.", Secret: true},
	{Name: "DISCORD_BOT_TOKEN", Purpose: "Discord bot token for notifications.", Secret: true},
	{Name: "DISCORD_OWNER_ID", Purpose: "Discord user ID that receives owner-only DMs and mutating commands.", Secret: false},
	{Name: "GITHUB_TOKEN", Purpose: "GitHub token for the self-updater (fallback to GO_TRADER_GITHUB_TOKEN).", Secret: true},
	{Name: "GO_TRADER_ALLOW_MISSING_STATE", Purpose: "Set to 1 to allow startup with no existing state DB (CheckStatePresence bypass).", Secret: false},
	{Name: "GO_TRADER_CASHFLOW_JOURNAL_ALARM", Purpose: "Set to 0/off/false/no to force the legacy trade-ledger drift basis for HL shared wallets instead of the #1100 exchange-sourced cash-flow journal (default on).", Secret: false},
	{Name: "GO_TRADER_DIRECTIONAL_CERT_PATH", Purpose: "Override path to the regime directional-certification artifact (#1085); default backtest/research/regime_directional_certifications.json.", Secret: false},
	{Name: "GO_TRADER_GITHUB_TOKEN", Purpose: "GitHub token for the self-updater (preferred over GITHUB_TOKEN).", Secret: true},
	{Name: "GO_TRADER_SERVICE", Purpose: "systemd unit name used by the updater's restart path.", Secret: false},
	{Name: "HYPERLIQUID_ACCOUNT_ADDRESS", Purpose: "Hyperliquid account address for live perps.", Secret: false},
	{Name: "HYPERLIQUID_SECRET_KEY", Purpose: "Hyperliquid signing key for live perps execution.", Secret: true},
	{Name: "OKX_API_KEY", Purpose: "OKX API key for live OKX spot.", Secret: true},
	{Name: "OKX_API_SECRET", Purpose: "OKX API secret for live OKX spot.", Secret: true},
	{Name: "OKX_PASSPHRASE", Purpose: "OKX API passphrase for live OKX spot.", Secret: true},
	{Name: "ROBINHOOD_PASSWORD", Purpose: "Robinhood password for live options.", Secret: true},
	{Name: "ROBINHOOD_TOTP_SECRET", Purpose: "Robinhood TOTP secret for live options 2FA.", Secret: true},
	{Name: "ROBINHOOD_USERNAME", Purpose: "Robinhood username for live options.", Secret: false},
	{Name: "STATUS_AUTH_TOKEN", Purpose: "Bearer token required for mutating status-server (POST /config) requests.", Secret: true},
	{Name: "TELEGRAM_BOT_TOKEN", Purpose: "Telegram bot token for notifications.", Secret: true},
	{Name: "TELEGRAM_OWNER_CHAT_ID", Purpose: "Telegram chat ID that receives owner notifications.", Secret: false},
	{Name: "TOPSTEP_ACCOUNT_ID", Purpose: "TopStep account ID for live futures.", Secret: false},
	{Name: "TOPSTEP_API_KEY", Purpose: "TopStep API key for live futures.", Secret: true},
	{Name: "TOPSTEP_API_SECRET", Purpose: "TopStep API secret for live futures.", Secret: true},
}

type agentConfigField struct {
	JSONName string `json:"json_name"`
	GoType   string `json:"go_type"`
	Optional bool   `json:"optional"`
}

type agentTableColumn struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	NotNull bool   `json:"not_null"`
	PK      bool   `json:"pk"`
}

type agentTable struct {
	Name    string             `json:"name"`
	Columns []agentTableColumn `json:"columns"`
}

type agentOpenPosition struct {
	StrategyID string  `json:"strategy_id"`
	Symbol     string  `json:"symbol"`
	Side       string  `json:"side"`
	Quantity   float64 `json:"quantity"`
	AvgCost    float64 `json:"avg_cost"`
	Regime     string  `json:"regime"`
}

type agentOpenOptionPosition struct {
	StrategyID string  `json:"strategy_id"`
	Underlying string  `json:"underlying"`
	OptionType string  `json:"option_type"`
	Strike     float64 `json:"strike"`
	Expiry     string  `json:"expiry"`
	Action     string  `json:"action"`
	Quantity   float64 `json:"quantity"`
}

type agentLiveState struct {
	Source              string                    `json:"source"`
	Note                string                    `json:"note"`
	DBPresent           bool                      `json:"db_present"`
	CycleCount          int64                     `json:"cycle_count"`
	OpenPositions       []agentOpenPosition       `json:"open_positions"`
	OpenOptionPositions []agentOpenOptionPosition `json:"open_option_positions"`
}

type agentStrategyInfo struct {
	ID               string   `json:"id"`
	Type             string   `json:"type"`
	Platform         string   `json:"platform"`
	Symbol           string   `json:"symbol,omitempty"`
	OpenModule       string   `json:"open_module"`
	CloseModule      string   `json:"close_module"`
	AllowedRegimes   []string `json:"allowed_regimes,omitempty"`
	RegimeGateWindow string   `json:"regime_gate_window,omitempty"`
}

type agentInfo struct {
	Version      string              `json:"version"`
	GeneratedAt  string              `json:"generated_at"`
	Capabilities []agentCommand      `json:"capabilities"`
	ConfigSchema []agentConfigField  `json:"config_schema"`
	EnvVars      []agentEnvVar       `json:"env_vars"`
	StateDB      []agentTable        `json:"state_db_schema"`
	LiveState    agentLiveState      `json:"live_state"`
	Strategies   []agentStrategyInfo `json:"strategies"`
}

func runAgentInfo(args []string) int {
	fs := flag.NewFlagSet("agent-info", flag.ContinueOnError)
	configPath := fs.String("config", "scheduler/config.json", "Path to config file")
	bootstrapMD := fs.Bool("bootstrap-md", false, "Write/refresh "+agentInfoGeneratedFile+" instead of dumping JSON to stdout")
	appendChangelog := fs.Bool("append-changelog", false, "When writing markdown, append a version-stamped changelog entry")
	output := fs.String("output", agentInfoGeneratedFile, "Markdown output path (with --bootstrap-md)")
	if err := fs.Parse(args); err != nil {
		return 2
	}

	cfg, err := func() (*Config, error) {
		realStdout := os.Stdout
		defer func() { os.Stdout = realStdout }()
		os.Stdout = os.Stderr
		return loadConfigSnapshot(*configPath)
	}()
	if err != nil {
		fmt.Fprintf(os.Stderr, "agent-info: warning: could not load config %s: %v\n", *configPath, err)
		cfg = nil
	}

	info := buildAgentInfo(cfg, Version, time.Now().UTC())

	if *bootstrapMD {
		md := renderAgentInfoMarkdown(info)
		if err := writeAgentInfoMarkdown(*output, md, *appendChangelog, info, time.Now().UTC()); err != nil {
			fmt.Fprintf(os.Stderr, "agent-info: failed to write %s: %v\n", *output, err)
			return 1
		}
		fmt.Fprintf(os.Stderr, "agent-info: wrote %s\n", *output)
		return 0
	}

	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	if err := enc.Encode(info); err != nil {
		fmt.Fprintf(os.Stderr, "agent-info: failed to encode JSON: %v\n", err)
		return 1
	}
	return 0
}

func loadConfigSnapshot(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read config: %w", err)
	}
	tmp, err := os.CreateTemp("", "agent-info-cfg-*.json")
	if err != nil {
		return nil, err
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return nil, err
	}
	if err := tmp.Close(); err != nil {
		return nil, err
	}
	return LoadConfig(tmpPath)
}

func buildAgentInfo(cfg *Config, version string, now time.Time) agentInfo {
	info := agentInfo{
		Version:      version,
		GeneratedAt:  now.Format(time.RFC3339),
		Capabilities: agentInfoCommands,
		ConfigSchema: reflectConfigSchema(),
		EnvVars:      resolveEnvVarPresence(agentInfoEnvVars),
		LiveState:    agentLiveState{Source: "none", Note: "no config loaded"},
	}

	if cfg != nil {
		info.Strategies = summarizeStrategies(cfg)
		dbPath := cfg.DBFile
		if dbPath == "" {
			dbPath = "scheduler/state.db"
		}
		statusPort := cfg.StatusPort
		if statusPort == 0 {
			statusPort = DefaultStatusPort
		}
		info.StateDB, info.LiveState = readStateDBReadOnly(dbPath, statusPort)
	}
	return info
}

func reflectConfigSchema() []agentConfigField {
	t := reflect.TypeOf(Config{})
	var out []agentConfigField
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		tag := f.Tag.Get("json")
		if tag == "" || tag == "-" {
			continue
		}
		parts := strings.Split(tag, ",")
		name := parts[0]
		if name == "" {
			continue
		}
		optional := false
		for _, p := range parts[1:] {
			if p == "omitempty" {
				optional = true
			}
		}
		out = append(out, agentConfigField{JSONName: name, GoType: f.Type.String(), Optional: optional})
	}
	return out
}

func resolveEnvVarPresence(vars []agentEnvVar) []agentEnvVar {
	out := make([]agentEnvVar, len(vars))
	for i, v := range vars {
		v.Set = os.Getenv(v.Name) != ""
		out[i] = v
	}
	return out
}

func summarizeStrategies(cfg *Config) []agentStrategyInfo {
	out := make([]agentStrategyInfo, 0, len(cfg.Strategies))
	for _, sc := range cfg.Strategies {
		closeModule := "(open-as-close)"
		if sc.CloseStrategy != nil && sc.CloseStrategy.Name != "" {
			closeModule = sc.CloseStrategy.Name
		}
		openModule := sc.OpenStrategy.Name
		if openModule == "" {
			openModule = sc.Script
		}
		out = append(out, agentStrategyInfo{
			ID:               sc.ID,
			Type:             sc.Type,
			Platform:         sc.Platform,
			Symbol:           sc.Symbol,
			OpenModule:       openModule,
			CloseModule:      closeModule,
			AllowedRegimes:   sc.AllowedRegimes,
			RegimeGateWindow: sc.RegimeGateWindow,
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

func readStateDBReadOnly(path string, statusPort int) ([]agentTable, agentLiveState) {
	live := agentLiveState{
		Source: "state.db snapshot",
		Note:   fmt.Sprintf("snapshot read from %s; may lag the running daemon. Query the status API on port %d for authoritative live state.", path, statusPort),
	}
	if _, err := os.Stat(path); err != nil {
		live.DBPresent = false
		live.Note = fmt.Sprintf("state DB %s not present yet; %s", path, live.Note)
		return nil, live
	}
	db, err := sql.Open("sqlite", "file:"+path+"?mode=ro&_pragma=busy_timeout(5000)")
	if err != nil {
		live.DBPresent = false
		return nil, live
	}
	defer db.Close()

	tables, err := readDBSchema(db)
	if err != nil {
		live.DBPresent = false
		return nil, live
	}
	positions, err := readOpenPositions(db)
	if err != nil {
		live.DBPresent = false
		live.Note = fmt.Sprintf("state DB %s present but open-position read failed (%v) — do not trust this snapshot; query the status API on port %d. %s", path, err, statusPort, live.Note)
		return tables, live
	}
	optionPositions, err := readOpenOptionPositions(db)
	if err != nil {
		live.DBPresent = false
		live.Note = fmt.Sprintf("state DB %s present but option-position read failed (%v) — do not trust this snapshot; query the status API on port %d. %s", path, err, statusPort, live.Note)
		return tables, live
	}
	live.DBPresent = true
	live.CycleCount = readCycleCount(db)
	live.OpenPositions = positions
	live.OpenOptionPositions = optionPositions
	return tables, live
}

func readDBSchema(db *sql.DB) ([]agentTable, error) {
	rows, err := db.Query(`SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name`)
	if err != nil {
		return nil, err
	}
	var names []string
	for rows.Next() {
		var n string
		if err := rows.Scan(&n); err != nil {
			rows.Close()
			return nil, err
		}
		names = append(names, n)
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return nil, err
	}

	var tables []agentTable
	for _, name := range names {
		cols, err := readTableColumns(db, name)
		if err != nil {
			return nil, err
		}
		tables = append(tables, agentTable{Name: name, Columns: cols})
	}
	return tables, nil
}

func readTableColumns(db *sql.DB, table string) ([]agentTableColumn, error) {
	rows, err := db.Query(fmt.Sprintf("PRAGMA table_info(%q)", table))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var cols []agentTableColumn
	for rows.Next() {
		var (
			cid       int
			name      string
			ctype     string
			notnull   int
			dfltValue sql.NullString
			pk        int
		)
		if err := rows.Scan(&cid, &name, &ctype, &notnull, &dfltValue, &pk); err != nil {
			return nil, err
		}
		cols = append(cols, agentTableColumn{Name: name, Type: ctype, NotNull: notnull != 0, PK: pk != 0})
	}
	return cols, rows.Err()
}

func readCycleCount(db *sql.DB) int64 {
	var c int64
	_ = db.QueryRow(`SELECT cycle_count FROM app_state WHERE id=1`).Scan(&c)
	return c
}

func readOpenPositions(db *sql.DB) ([]agentOpenPosition, error) {
	rows, err := db.Query(`SELECT strategy_id, symbol, side, quantity, avg_cost, regime FROM positions ORDER BY strategy_id, symbol`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []agentOpenPosition
	for rows.Next() {
		var p agentOpenPosition
		if err := rows.Scan(&p.StrategyID, &p.Symbol, &p.Side, &p.Quantity, &p.AvgCost, &p.Regime); err != nil {
			return nil, err
		}
		out = append(out, p)
	}
	return out, rows.Err()
}

func readOpenOptionPositions(db *sql.DB) ([]agentOpenOptionPosition, error) {
	rows, err := db.Query(`SELECT strategy_id, underlying, option_type, strike, expiry, action, quantity FROM option_positions ORDER BY strategy_id, underlying, expiry`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []agentOpenOptionPosition
	for rows.Next() {
		var p agentOpenOptionPosition
		if err := rows.Scan(&p.StrategyID, &p.Underlying, &p.OptionType, &p.Strike, &p.Expiry, &p.Action, &p.Quantity); err != nil {
			return nil, err
		}
		out = append(out, p)
	}
	return out, rows.Err()
}

func renderAgentInfoMarkdown(info agentInfo) string {
	var b strings.Builder
	b.WriteString(agentInfoMarkdownHeader)
	b.WriteString("\n\n# go-trader — agent capabilities\n\n")
	fmt.Fprintf(&b, "Version: `%s`  ·  Generated: %s\n\n", info.Version, info.GeneratedAt)

	b.WriteString("## Capabilities (CLI subcommands)\n\n")
	for _, c := range info.Capabilities {
		fmt.Fprintf(&b, "- **%s** — %s\n  - `%s`\n", c.Name, c.Summary, c.Usage)
	}

	b.WriteString("\n## Config schema (`config.json` top-level keys)\n\n")
	b.WriteString("| key | type | optional |\n|---|---|---|\n")
	for _, f := range info.ConfigSchema {
		fmt.Fprintf(&b, "| `%s` | `%s` | %v |\n", f.JSONName, f.GoType, f.Optional)
	}

	b.WriteString("\n## Environment variables\n\n")
	b.WriteString("| var | secret | purpose |\n|---|---|---|\n")
	for _, v := range info.EnvVars {
		fmt.Fprintf(&b, "| `%s` | %v | %s |\n", v.Name, v.Secret, v.Purpose)
	}

	b.WriteString("\n## State DB schema\n\n")
	if len(info.StateDB) == 0 {
		b.WriteString("_No state DB found (it is created on first daemon run)._\n")
	} else {
		for _, t := range info.StateDB {
			fmt.Fprintf(&b, "- **%s**: ", t.Name)
			names := make([]string, 0, len(t.Columns))
			for _, c := range t.Columns {
				names = append(names, c.Name)
			}
			b.WriteString("`" + strings.Join(names, "`, `") + "`\n")
		}
	}

	b.WriteString("\n## Strategies (open/close decision modules)\n\n")
	if len(info.Strategies) == 0 {
		b.WriteString("_No strategies configured._\n")
	} else {
		b.WriteString("| id | type | platform | open | close | regime gate |\n|---|---|---|---|---|---|\n")
		for _, s := range info.Strategies {
			fmt.Fprintf(&b, "| `%s` | %s | %s | `%s` | `%s` | %s |\n",
				s.ID, s.Type, s.Platform, s.OpenModule, s.CloseModule, strings.Join(s.AllowedRegimes, ","))
		}
	}

	b.WriteString("\n## Live state (DB snapshot)\n\n")
	fmt.Fprintf(&b, "%s\n\n", info.LiveState.Note)
	if info.LiveState.DBPresent {
		fmt.Fprintf(&b, "Cycle count: %d  ·  Open positions: %d (perps/spot/futures) + %d option legs\n",
			info.LiveState.CycleCount, len(info.LiveState.OpenPositions), len(info.LiveState.OpenOptionPositions))
	}

	return b.String()
}

const agentInfoChangelogMaxEntries = 50

func writeAgentInfoMarkdown(path, md string, appendChangelog bool, info agentInfo, now time.Time) error {
	const changelogMarker = "## Changelog\n"

	var entries []string
	if prev, err := os.ReadFile(path); err == nil {
		if idx := strings.Index(string(prev), changelogMarker); idx >= 0 {
			for _, line := range strings.Split(string(prev)[idx+len(changelogMarker):], "\n") {
				if strings.HasPrefix(strings.TrimSpace(line), "- ") {
					entries = append(entries, strings.TrimRight(line, "\r"))
				}
			}
		}
	}

	if appendChangelog {
		entry := fmt.Sprintf("- %s — version `%s` (%d strategies, %d open positions)",
			now.Format("2006-01-02"), info.Version, len(info.Strategies), len(info.LiveState.OpenPositions))
		entries = append([]string{entry}, entries...)
	}

	if len(entries) > agentInfoChangelogMaxEntries {
		entries = entries[:agentInfoChangelogMaxEntries]
	}

	if len(entries) == 0 {
		return os.WriteFile(path, []byte(md), 0644)
	}

	var b strings.Builder
	b.WriteString(md)
	b.WriteString("\n")
	b.WriteString(changelogMarker)
	b.WriteString("\n")
	for _, e := range entries {
		b.WriteString(e)
		b.WriteString("\n")
	}
	return os.WriteFile(path, []byte(b.String()), 0644)
}
