name: Discord Release Notification

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Discord
        uses: SethCohen/github-releases-to-discord@v1.20.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: "2105893"
          username: "go-trader"
